name: Analizar código PHP

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente

env:
  NODE_OPTIONS: "--unhandled-rejections=strict"

jobs:
  analizar-codigo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2.3.1
      with:
        node-version: '14.20'

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Actualizar dependencias de Composer
      run: composer update

    - name: Instalar dependencias
      run: |
        npm install
        composer install

    - name: Ejecutar PHPStan
      run: vendor/bin/phpstan analyze --no-progress --memory-limit=2G

    - name: Notificar en caso de errores
      if: failure()
      run: echo "Hubo errores al analizar el código PHP en el repositorio."
